---
title: "Depth of hierarchy2"
author: "Seiya"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: 2
    number_sections: no
    theme: flatly
    highlight: textmate
    df_print: "paged"
    fig_caption: yes
    fig_width: 8
    fig_height: 4
    md_extensions: -ascii_identifiers
    keep_md: yes
    dev: png
editor_options: 
  chunk_output_type: inline
  markdown:
    wrap: 72
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, comment="", warning=FALSE, message=FALSE, fig.align="center", cache=T, tidy=F, fig.pos = 'H', dpi = 400)
knitr::set_alias(fh="fig.height", fw="fig.width", fc="fig.cap")
#knitr::opts_chunk$set(class.source = "fold-show")

library(tidyverse)
library(DT)
library(lmerTest)
library(emmeans)
library(merTools)
library(betareg)
library(ggplot2)
library(stringdist)

my_theme <- theme(axis.text = element_text(size = 20, family="Arial"),
                  axis.title = element_text(size = 20, family="Arial"),
                  panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.background = element_blank(),
                  axis.line=element_line(colour = "black"),
                  axis.ticks=element_line(colour = "black"),
                  )
theme_set(my_theme)
```

```{r}
# define variables
num_sequences <- 2 # number of sequences
size_sets <- 8 # Number of trials included in one set
num_pairs <- 71 # number of pairs
condition <- 3
# 1 -> Adult-pair
# 2 -> Child-pair
# 3 -> Adult-Child
len_sequence <- 13 # the length of sequence

num_trial <- num_sequences*size_sets #number of trials 14*4=56
```

```{r}
dir <- "../Hierarchy_condX.csv"
dir <- gsub("X",as.character(condition), dir)
df <- read.csv(dir, header = T)
#df$generation <- as.factor(df$generation)
df$pair_ID <- as.factor(df$pair_ID)
df$age_f <- as.factor(df$age)

number <- (size_sets*num_sequences+num_sequences)*2*num_pairs
```

```{r}
#Adult-Adult: 1
#Adult-Child: 2
#Child-Child: 3

assign_value <- function(generation) {
  if (all(generation == "Adult")) {
    return(1)
  } else if (all(generation == "Child")) {
    return(2)
  } else {
    return(3)
  }
}

df <- df[, colnames(df) != "condition"]
result <- df %>%
  group_by(pair_ID) %>%
  summarise(condition = assign_value(generation))

df <- df %>%
  left_join(result, by = "pair_ID")
df$individual_ID <- as.factor(df$individual_ID)
df$pair_ID <- as.factor(df$pair_ID)
df$condition <- as.factor(df$condition)

```

```{r, eval=FALSE}
subset(df, trial==1&individual_ID==0) %>% count(condition)
# condition  n
#         1 19
#         2 26
#         3 26

demographic <- group_by(subset(df, trial==1), condition) %>% 
  summarise_at(vars(age), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))

# condition  mean    sd    se
# 1         40.9   6.71 1.09 
# 2          8.25  1.66 0.230
# 3         25.3  18.3  2.53 
```

# Analysis (linear regression)


```{r}
Depth_of_hierarchy2.withinset.byindi <- group_by(df, pair_ID, individual_ID, within_trial) %>% 
  summarise_at(vars(Depth_of_hierarchy2), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
```

```{r}
Depth_of_hierarchy2.withinset.bypair <- group_by(df, pair_ID, within_trial) %>% 
  summarise_at(vars(Depth_of_hierarchy2), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
```

```{r}
Depth_of_hierarchy2.withinset <- group_by(df, within_trial) %>% 
  summarise_at(vars(Depth_of_hierarchy2), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
```

```{r}
Depth_of_hierarchy2.withinset
```

## Plot data

```{r}
# plot graph
#condition 1: Adults
Depth_of_hierarchy2.withinset_1 <- group_by(subset(df,within_trial!=0&condition==1), within_trial) %>% 
  summarise_at(vars(Depth_of_hierarchy2), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
Depth_of_hierarchy2.withinset_1$condition <- "1"

#condition 2: Children
Depth_of_hierarchy2.withinset_2 <- group_by(subset(df,within_trial!=0&condition==2), within_trial) %>% 
  summarise_at(vars(Depth_of_hierarchy2), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
Depth_of_hierarchy2.withinset_2$condition <- "2"

#condition 3: Adult-Child
Depth_of_hierarchy2.withinset_3 <- group_by(subset(df,within_trial!=0&condition==3), within_trial) %>% 
  summarise_at(vars(Depth_of_hierarchy2), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
Depth_of_hierarchy2.withinset_3$condition <- "3"

# plot graph
ggplot() +
  geom_line(data = Depth_of_hierarchy2.withinset_1, aes(x = within_trial, y = mean, color=condition)) +
  geom_errorbar(data = Depth_of_hierarchy2.withinset_1, aes(x = within_trial, y = mean, ymin = mean - se, ymax = mean + se),width = .1, color = "gray") +
  geom_line(data = Depth_of_hierarchy2.withinset_2, aes(x = within_trial, y = mean,color=condition)) +
  geom_errorbar(data = Depth_of_hierarchy2.withinset_2, aes(x = within_trial, y = mean, ymin = mean - se, ymax = mean + se),width = .1, color = "gray") +
  geom_line(data = Depth_of_hierarchy2.withinset_3, aes(x = within_trial, y = mean,color=condition)) +
  geom_errorbar(data = Depth_of_hierarchy2.withinset_3, aes(x = within_trial, y = mean, ymin = mean - se, ymax = mean + se),width = .1, color = "gray") +
  labs(color = "condition") +
  scale_color_hue(name = "condition", labels = c("1" = "Adults", "2" ="Children", "3"="Adult-Child") ) +
  theme(legend.position = c(0.80, 0.35), legend.justification = c(0,1)) +
  xlab("Trial") + 
  ylab("Depth_of_hierarchy2") + 
  ylim(0, 1.5)
ggsave("0_Figures/Depth_of_hierarchy2.png", width = 8, height = 4, dpi=400)
```

## Fitting to single regression

$$Depth_of_hierarchy2 = \alpha + \beta_1 \cdot trial + \beta_2 \cdot condition$$

```{r}
## dependent：Depth_of_hierarchy2
## independent：within_trial
## random intercept：pair_ID
fit1 <- lmer(Depth_of_hierarchy2~within_trial+condition  + (1|pair_ID), data = df)
summary(fit1)
```

$$Depth_of_hierarchy2 = \alpha + \beta_1 \cdot trial + \beta_2 \cdot condition + \beta_1 \cdot \beta2$$

```{r}
## dependent：Depth_of_hierarchy2
## independent：within_trial
## random intercept：pair_ID
fit1.1 <- lmer(Depth_of_hierarchy2~within_trial+condition + within_trial*condition + (1|pair_ID), data = df)
summary(fit1.1)
```



```{r}
sessionInfo()
```