---
title: "Regularization and Depth of hierarchy"
author: "Seiya"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: 2
    number_sections: no
    theme: flatly
    highlight: textmate
    df_print: "paged"
    fig_caption: yes
    fig_width: 8
    fig_height: 8
    md_extensions: -ascii_identifiers
    keep_md: yes
    dev: png
editor_options: 
  chunk_output_type: inline
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, comment="", warning=FALSE, message=FALSE, fig.align="center", cache=T, tidy=F, fig.pos = 'H', dpi = 400)
knitr::set_alias(fh="fig.height", fw="fig.width", fc="fig.cap")
#knitr::opts_chunk$set(class.source = "fold-show")

library(tidyverse)
library(DT)
library(lmerTest)
library(emmeans)
library(merTools)
library(betareg)
library(ggplot2)
library(stringdist)

my_theme <- theme(axis.text = element_text(size = 20, family="Arial"),
                  axis.title = element_text(size = 20, family="Arial"),
                  panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.background = element_blank(),
                  axis.line=element_line(colour = "black"),
                  axis.ticks=element_line(colour = "black"),
                  )
theme_set(my_theme)
```

```{r}
# define variables
num_sequences <- 2 # number of sequences
size_sets <- 8 # Number of trials included in one set
num_pairs <- 71 # number of pairs
condition <- 3
# 1 -> Adult-pair
# 2 -> Child-pair
# 3 -> Adult-Child
len_sequence <- 13 # the length of sequence

num_trial <- num_sequences*size_sets
```


```{r}
dir <- "../Hierarchy_condX.csv"
dir <- gsub("X",as.character(condition), dir)
df <- read.csv(dir, header = T)
#df$generation <- as.factor(df$generation)
df$pair_ID <- as.factor(df$pair_ID)
df$age_f <- as.factor(df$age)

number <- (size_sets*num_sequences+num_sequences)*2*num_pairs
```

```{r}
#Adult-Adult: 1
#Adult-Child: 2
#Child-Child: 3

assign_value <- function(generation) {
  if (all(generation == "Adult")) {
    return(1)
  } else if (all(generation == "Child")) {
    return(2)
  } else {
    return(3)
  }
}

df <- df[, colnames(df) != "condition"]
result <- df %>%
  group_by(pair_ID) %>%
  summarise(condition = assign_value(generation))

df <- df %>%
  left_join(result, by = "pair_ID")

df$condition <- as.factor(df$condition)
```

```{r, eval=FALSE}
subset(df, trial==1&individual_ID==0) %>% count(condition)
# condition  n
#         1 19
#         2 26
#         3 26

demographic <- group_by(subset(df, trial==1), condition) %>% 
  summarise_at(vars(age), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))

# condition  mean    sd    se
# 1         40.9   6.71 1.09 
# 2          8.25  1.66 0.230
# 3         25.3  18.3  2.53 

df <- df %>%
  group_by(pair_ID) %>%
  mutate(individual_ID = ifelse(age == min(age) & n_distinct(age) == 1,
                                ifelse(row_number() == 1, 0, 1),  # 行番号で区別
                                ifelse(age == min(age), 0, 1)))

```

```{r, cache=FALSE}
datatable(df)
summary(df)
```



```{r}
df_regular <- read.csv("../df_regular.csv", header = T)
df_regular$pair_ID <- as.factor(df_regular$pair_ID)
df_regular$condition <- as.factor(df_regular$condition)
```

```{r}
#Adult-Adult: 1
#Adult-Child: 2
#Child-Child: 3

assign_value <- function(generation) {
  if (all(generation == "Adult")) {
    return(1)
  } else if (all(generation == "Child")) {
    return(2)
  } else {
    return(3)
  }
}

df_regular <- df_regular[, colnames(df_regular) != "condition"]
result <- df_regular %>%
  group_by(pair_ID) %>%
  summarise(condition = assign_value(generation))

df_regular <- df_regular %>%
  left_join(result, by = "pair_ID")

df_regular$condition <- as.factor(df_regular$condition)
```

```{r}
regular.withinset.byindi <- group_by(df_regular, condition,pair_ID, within_trial) %>% 
  summarise_at(vars(regularization), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))

regular.withinset.byindi$condition <- as.factor(regular.withinset.byindi$condition)

```

```{r}
regular.withinset <- group_by(df_regular, within_trial) %>% 
  summarise_at(vars(regularization), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
```

```{r}
regular.withinset.bycond <- group_by(df_regular, condition, within_trial) %>% 
  summarise_at(vars(regularization), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
regular.withinset.bycond$condition <- as.factor(regular.withinset.bycond$condition)

```


```{r}
regular.withinset.byindi <- group_by(df_regular, condition,pair_ID, within_trial) %>% 
  summarise_at(vars(regularization), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))

regular.withinset.byindi$condition <- as.factor(regular.withinset.byindi$condition)

```

```{r}
regular.withinset <- group_by(df_regular, within_trial) %>% 
  summarise_at(vars(regularization), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
```

```{r}
regular.withinset.bycond <- group_by(df_regular, condition, within_trial) %>% 
  summarise_at(vars(regularization), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
regular.withinset.bycond$condition <- as.factor(regular.withinset.bycond$condition)

```


# regularization all

* Use the data of hierarchy only at trial 8
* Calculate mean regularization among all trials


## Plot data

```{r}
df_regular.no1 <- subset(df_regular, within_trial!=1)
regularization.byindi <- group_by(df_regular.no1, pair_ID, individual_ID) %>% 
  summarise_at(vars(regularization), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
regularization_depth8 <- subset(regularization.byindi, individual_ID==0)[,"pair_ID"]
regularization_depth8["regularization0"] <- subset(regularization.byindi, individual_ID==0)[,"mean"]
regularization_depth8["regularization1"] <- subset(regularization.byindi, individual_ID==1)[,"mean"]

depth.t8.bypair <- group_by(subset(df,within_trial==8), pair_ID, ) %>% 
  summarise_at(vars(Depth_of_hierarchy2), list(mean = ~mean(.), 
                     sd = ~sd(.), 
                     se = ~sd(.)/sqrt(length(.))))
regularization_depth8["Depth_of_hierarchy"] <- depth.t8.bypair$mean

regularization_depth8$condition <- subset(df_regular.no1,within_trial==2&set_number==1&individual_ID==0)$condition

middle <- mean(regularization_depth8$Depth_of_hierarchy)
cat("reference line of depth:", middle)
```

```{r}
# plot graph
ggplot(data = regularization_depth8, aes(x = regularization0, y = regularization1, color = Depth_of_hierarchy, fill = Depth_of_hierarchy, shape = factor(condition))) +
  geom_point(size = 3.0,
             position = position_jitterdodge(jitter.width = 0.1, jitter.height = 0.1)) +
  labs(x = "regularization of individual 0", y = "regularization of individual 1") +
  xlim(0.00, 1.00) +
  ylim(0.00, 1.00) +
  #theme(legend.position = c(0.05, 1.00), legend.justification = c(0,1)) +
  scale_shape_manual(values = c(21, 22, 23), labels = c("Adults", "Children", "Adult-Child")) +
  scale_color_gradient2(midpoint = middle, low = "blue", mid = "gray", high = "red", limits = c(0.0, 3.0)) +
  scale_fill_gradient2(midpoint = middle, low = "blue", mid = "gray", high = "red", limits = c(0.0, 3.0)) +
  guides(fill = guide_colorbar(title = "Depth of hierarchy"), 
         color = guide_colorbar(title = "Depth of hierarchy"), 
         shape = guide_legend(title = "Condition"))

ggsave("0_Figures/regularization_Depth8.png", width = 8, height = 8, dpi=400)

```


## Difference of regularization

* To integrate regularization of two individuals, calculate the difference of them and enter the difference as independent variable

$$Depth of hierarchy ~ \alpha + A_{dif} \beta$$


```{r}
regularization_depth8$diff <- abs(regularization_depth8$regularization0 - regularization_depth8$regularization1)
```

```{r}
# plot graph
ggplot(data=regularization_depth8, aes(x = diff, y = Depth_of_hierarchy, color = condition)) +
  geom_point(size=3.0
             , position = position_jitter(width = 0.02, height = 0.02)
             ) +
  xlim(0.00,0.30) +
  ylim(0.00,3.00) +
  xlab("Difference of regularization") +
  ylab("Depth of hierarchy at trial 8") +
  labs(color = "condition") +
  scale_color_hue(name = "condition", labels = c("1" = "Adults", "2" ="Children", "3"="Adult-Child") )
ggsave("0_Figures/Diffregularization_Depth8.png", width = 8, height = 8, dpi=400)

```


```{r}
## dependent：Depth_of_hierarchy (trial 8)
## independent：regularization_diff
fit1_diff <- lm(Depth_of_hierarchy ~ diff, data = regularization_depth8)
summary(fit1_diff)

```

# Info

```{r}
sessionInfo()
```